name: done
description: Done auth services
homepage: https://github.com/imandaneshi/done-microservices

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  async: ^2.2.0
  grpc: ^2.1.2
  protobuf: ^0.14.1
  redis: ^1.2.1

dev_dependencies:
  test: ^1.6.4